- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'
    - 'beat'
- platform: template
  sensors:
    sunset_time:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting)  | timestamp_custom("%H:%M") }}'

- platform: template
  sensors:
    sunrise_time:
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising)  | timestamp_custom("%H:%M") }}'

- platform: onewire
  names:
    28-0316544480ff : Vloer Temperatuur  

# - platform: p2000
#   regios: 20
#   disciplines: 1,2,3,4
#   radius: 15000
#   scan_interval: 20
  
# - platform: p2000
#   name: Prinsenbeek
#   regios: 20
#   disciplines: 1,2,3,4
#   radius: 1000
#   scan_interval: 10
#   latitude: 51.596499
#   longitude: 4.704773

# - platform: mijnafvalwijzer
#   postcode: '4841JX'
#   huisnummer: '9'
#   toevoeging: ''
#   label_geen: 'Geen'

- platform: afvalwijzer
  url: 'mijnafvalwijzer.nl'
  postcode: '4841JX'
  huisnummer: '9'
  toevoeging: ''
  label_geen: 'Geen'


- platform: pi_hole
  host: 192.168.1.110
- platform: template
  sensors:
    pihole_queries_today:
      value_template: '{{ states.sensor.pihole.attributes.queries_today }}'
      friendly_name: 'Queries Today'
    pihole_percentage_today:
      value_template: '{{ states.sensor.pihole.attributes.percentage_today }}'
      friendly_name: 'Percentage Today'
    pihole_domains_blocked:
      value_template: '{{ states.sensor.pihole.attributes.domains_blocked }}'
      friendly_name: 'Domains Blocked'
    yamaha_model_name:
      value_template: '{{ states.sensor.yamaha.attributes["device_id"] }}'
      friendly_name: 'Device name'
    yamaha_dab_now_playing:
      value_template: '{{ state_attr("sensor.nowplayinginfo", "dab")["dls"]}}'
      friendly_name: 'Now Playing on DAB+'

    yamaha_dab_stationinfo:
      value_template: '{{ state_attr("sensor.nowplayinginfo", "dab")["service_label"]}}'
      friendly_name: 'Now Playing on DAB+'


# 192.168.1.107 : Soundbar
# 192.168.1.108 : Kitchen
# 192.168.1.109 : Study


# - platform: rest
#   name: yamaha
#   json_attributes:
#     - model_name
#     - device_id
#   resource: http://192.168.1.117/YamahaExtendedControl/v1/system/getDeviceInfo
#   method: GET
#   value_template: '{{value_json.model_name}}'

# - platform: rest
#   name: nowplayinginfo
#   json_attributes:
#     - dab
#   resource: http://192.168.1.108/YamahaExtendedControl/v1/tuner/getPlayInfo
#   method: GET
#   value_template: '{{value_json.dab.dls}}'

# - platform: rest
#   name: volumestudy
#   resource: http://192.168.1.109/YamahaExtendedControl/v1/main/getStatus
#   method: GET
#   value_template: '{{value_json.volume}}'

# - platform: rest
#   name: maxvolumestudy
#   resource: http://192.168.1.109/YamahaExtendedControl/v1/main/getStatus
#   method: GET
#   value_template: '{{value_json.max_volume}}'

# - platform: rest
#   name: volumekitchen
#   resource: http://192.168.1.108/YamahaExtendedControl/v1/main/getStatus
#   method: GET
#   value_template: '{{value_json.volume}}'

# - platform: rest
#   name: maxvolumekitchen
#   resource: http://192.168.1.108/YamahaExtendedControl/v1/main/getStatus
#   method: GET
#   value_template: '{{value_json.max_volume}}'

# - platform: rest
#   name: volumeliving
#   resource: http://192.168.1.107/YamahaExtendedControl/v1/main/getStatus
#   method: GET
#   value_template: '{{value_json.volume}}'

# - platform: rest
#   name: maxvolumeliving
#   resource: http://192.168.1.107/YamahaExtendedControl/v1/main/getStatus
#   method: GET
#   value_template: '{{value_json.max_volume}}'  
  